from pathlib import Path

ROOT_DIR = Path(__file__).parent.parent
DATA_DIR = ROOT_DIR / "data"
LOGS_DIR = ROOT_DIR / "logs"
MODELS_DIR = ROOT_DIR / "models"
SRC_DIR = ROOT_DIR / "src"

SENTIMENT_BATCH_SIZE = 16
SENTIMENT_MAX_LENGTH = 512

TOPIC_MIN_TOPIC_SIZE = 4
TOPIC_UMAP_N_NEIGHBORS = 15
TOPIC_UMAP_N_COMPONENTS = 2
TOPIC_UMAP_MIN_DIST = 0.1
TOPIC_UMAP_METRIC = "cosine"
TOPIC_RANDOM_SEED = 42
TOPIC_VECTORIZER_MAX_DF = 0.85
TOPIC_VECTORIZER_MIN_DF = 2
TOPIC_EMBEDDING_MODEL = "cl-nagoya/ruri-v3-310m"
TOPIC_EMBEDDING_BATCH_SIZE_CUDA = 64
TOPIC_EMBEDDING_BATCH_SIZE_CPU = 16

CLUSTER_UMAP_N_COMPONENTS = 2
CLUSTER_UMAP_N_NEIGHBORS = 15
CLUSTER_UMAP_MIN_DIST = 0.0
CLUSTER_UMAP_METRIC = "cosine"
CLUSTER_RANDOM_SEED = 42
CLUSTER_HDBSCAN_MIN_CLUSTER_SIZE = 20
CLUSTER_HDBSCAN_MIN_SAMPLES = 5

KMEANS_RANDOM_SEED = 42
KMEANS_N_INIT = 10
KMEANS_K_RANGE = range(2, 11)
