from pathlib import Path

# 封装Path对象
# 通过Path对象找到目录
ROOT_DIR = Path(__file__).parent.parent
DATA_DIR = ROOT_DIR / "data"
LOGS_DIR = ROOT_DIR / "logs"
MODELS_DIR = ROOT_DIR / "models"
SRC_DIR = ROOT_DIR / "src"

# 情感分析参数
SENTIMENT_BATCH_SIZE = 16
SENTIMENT_MAX_LENGTH = 512

# 话题建模参数
TOPIC_MIN_TOPIC_SIZE = 4
TOPIC_UMAP_N_NEIGHBORS = 20
TOPIC_UMAP_N_COMPONENTS = 8
TOPIC_UMAP_MIN_DIST = 0.0
TOPIC_UMAP_METRIC = "cosine"
TOPIC_RANDOM_SEED = 42
TOPIC_VECTORIZER_MAX_DF = 0.95
TOPIC_VECTORIZER_MIN_DF = 1
TOPIC_EMBEDDING_BATCH_SIZE_CUDA = 64
TOPIC_EMBEDDING_BATCH_SIZE_CPU = 16

# 聚类分析参数 (UMAP + HDBSCAN)
CLUSTER_UMAP_N_COMPONENTS = 2
CLUSTER_UMAP_N_NEIGHBORS = 15
CLUSTER_UMAP_MIN_DIST = 0.0
CLUSTER_UMAP_METRIC = "cosine"
CLUSTER_RANDOM_SEED = 42
CLUSTER_HDBSCAN_MIN_CLUSTER_SIZE = 20
CLUSTER_HDBSCAN_MIN_SAMPLES = 5

# KMeans 参数
KMEANS_RANDOM_SEED = 42
KMEANS_N_INIT = 10
KMEANS_K_RANGE = range(2, 11)
